[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/assets/AdminUsers-DybC3eRH.js"
  to = "/assets/AdminUsers-ypgX3BOh.js"
  status = 301

[[redirects]]
  from = "/assets/AdminUsers-uVJGCwIS.js"
  to = "/assets/AdminUsers-ypgX3BOh.js"
  status = 301

[[redirects]]
  from = "/assets/AdminUsers-*.js"
  to = "/assets/AdminUsers-DlTPqurk.js"
  status = 301

[[redirects]]
  from = "/assets/AdminProfessionals-*.js"
  to = "/assets/AdminProfessionals-mQNxj0W2.js"
  status = 301

[[redirects]]
  from = "/assets/AdminPatients-*.js"
  to = "/assets/AdminPatients-C1hbI-1D.js"
  status = 301

[[redirects]]
  from = "/assets/AdminAppointments-*.js"
  to = "/assets/AdminAppointments-DsW3Gk_M.js"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 