[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/assets/AdminUsers-*.js"
  to = "/assets/AdminUsers-t086xzSd.js"
  status = 301

[[redirects]]
  from = "/assets/AdminProfessionals-*.js"
  to = "/assets/AdminProfessionals-Be8Mtvsg.js"
  status = 301

[[redirects]]
  from = "/assets/AdminPatients-*.js"
  to = "/assets/AdminPatients-CYBrx2rw.js"
  status = 301

[[redirects]]
  from = "/assets/StableProfessionalSettings-*.js"
  to = "/assets/StableProfessionalSettings-DtEWIw4g.js"
  status = 301

[[redirects]]
  from = "/assets/AvailabilityManagement-*.js"
  to = "/assets/AvailabilityManagement-DaxDZNGB.js"
  status = 301

[[redirects]]
  from = "/assets/AdminAppointments-*.js"
  to = "/assets/AdminAppointments-i5DwowDc.js"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 